[package]
name = "gitall"
version = "0.2.2"
authors = ["Matthew Mahnke <mmahnke18@gmail.com>"]
edition = "2018"
description = "Executes git(1) commands in repos below a parent directory"
documentation = "https://github.com/mattmahn/gitall.rs"
repository = "https://github.com/mattmahn/gitall.rs"
readme = "README.md"
license = "Unlicense OR MIT"
categories = ["command-line-utilities"]
build = "build.rs"

[badges]
travis-ci = { repository = "mattmahn/gitall.rs", branch = "master" }

[build-dependencies]
clap = "~2.32.0"

[dependencies]
atty = "~0.2.11"
clap = "~2.32.0"
num_cpus = "1.9.0"
rayon = "1.0.3"
termcolor = "1.0.4"
walkdir = "2"
